# **Trading Strategies and Signals**

### Initial Imports:

In [1]:
import numpy as np
import pandas as pd


from pathlib import Path
import requests



import warnings
warnings.filterwarnings('ignore')

In [2]:
# !pip install yfinance
import yfinance as yf

### Initialization:

In [3]:
# User Inputs for Stock Ticker and Timeframe:
ticker = "AAPL"
start="2001-01-01"
end="2021-1-1"

In [4]:
# EMA & EMA of returns volatility:
short_window = 12
long_window = 26

# Bollinger Band:
bollinger_window = 20

# On Balance Volumn:
OBV_ewm_window = 20

### Download Stock Data from Yahoo Finance and Calculate Returns:

In [5]:
def get_stock_returns (ticker, start, end):
    ''' 
    Taking ticker, start data, end data,
    Download stock data from yahoo finance,
    Return a list of two dataframes:
    1. the original dataframe
    2. a modified dataframe which contains Adj Close, Volume, and calculated daily returns.
    '''
    df_yfinance = yf.download(ticker, start, end)
    df_returns = df_yfinance[["Adj Close", "Volume"]]
    # calculate returns according to the ticker name
    df_returns["Returns"] = df_yfinance[["Adj Close"]].pct_change()
    df_returns.dropna(inplace=True)
    # rename columns according to the ticker name
    df_returns.columns = [(f"{ticker}_"+ column) for column in df_returns.columns]
    return [df_yfinance, df_returns]

In [6]:
# Inspection of download stock data
original_data, returns_df = get_stock_returns(ticker, start, end)

display(original_data.head())
print(" ")
display(original_data.tail())
print(" ")
print("***************** Check Data Quality *****************")
print(original_data.info())
print(" ")
print(original_data.index)
print(" ")
print("***************** Check Returns Data *****************")
display(returns_df.head())
print(returns_df.shape)

[*********************100%***********************]  1 of 1 completed

                Open      High       Low     Close  Adj Close     Volume
Date
2001-01-02  0.265625  0.272321  0.260045  0.265625   0.228800  452312000
2001-01-03  0.258929  0.297991  0.257813  0.292411   0.251872  817073600
2001-01-04  0.323940  0.330357  0.300223  0.304688   0.262447  739396000
2001-01-05  0.302455  0.310268  0.286830  0.292411   0.251872  412356000
2001-01-08  0.302455  0.303292  0.284598  0.295759   0.254756  373699200

,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,
2020-12-23,132.160004,132.429993,130.779999,130.960007,130.764603,88223700
2020-12-24,131.320007,133.460007,131.100006,131.970001,131.773087,54930100
2020-12-28,133.990005,137.339996,133.509995,136.690002,136.486053,124486200
2020-12-29,138.050003,138.789993,134.339996,134.869995,134.668762,121047300
2020-12-30,135.580002,135.990005,133.399994,133.720001,133.520477,96452100

***************** Check Data Quality *****************
<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 5031 entries, 2001-01-02 to 2020-12-30
Data columns (total 6 columns):
Open         5031 non-null float64
High         5031 non-null float64
Low          5031 non-null float64
Close        5031 non-null float64
Adj Close    5031 non-null float64
Volume       5031 non-null int64
dtypes: float64(5), int64(1)
memory usage: 275.1 KB
None

DatetimeIndex(['2001-01-02', '2001-01-03', '2001-01-04', '2001-01-05',
               '2001-01-08', '2001-01-09', '2001-01-10', '2001-01-11',
               '2001-01-12', '2001-01-16',
               ...
               '2020-12-16', '2020-12-17', '2020-12-18', '2020-12-21',
               '2020-12-22', '2020-12-23', '2020-12-24', '2020-12-28',
               '2020-12-29', '2020-12-30'],
              dtype='datetime64[ns]', name='Date', length=5031, freq=None)

***************** Check Returns Data *****************

            AAPL_Adj Close  AAPL_Volume  AAPL_Returns
Date
2001-01-03        0.251872    817073600      0.100842
2001-01-04        0.262447    739396000      0.041985
2001-01-05        0.251872    412356000     -0.040294
2001-01-08        0.254756    373699200      0.011450
2001-01-09        0.264370    588929600      0.037737

(5030, 3)

### **Trading Signals:**

#### 1. Exponential Moving Average (EMA) Crossover Strategy:
When the short period EMA cuts above the longer period EMA, it is a bullish signal.
<br>When the short period EMA cuts below the longer period EMA, it is a bearish signal. 

Commonly used periods are 12 and 26 periods. (*set as default in this notebook*)

Although, it indicates present trend of the stock, there are many limitations such as:
<br>a. It has the lagging indicator as it relies on some past price movements. 
<br>b. It is more vulnerable to false signals and getting whipsawed back and forth

https://www.warriortrading.com/exponential-moving-average/<br>
https://www.perfecttrendsystem.com/blog_mt4/en/ema-12-ema-26-trading-strategy

In [7]:
def ema(short_window=12, long_window=26):
    df_ema = pd.DataFrame()
    # Construct a `Fast` and `Slow` Exponential Moving Average from short and long windows, respectively
    df_ema['fast_close'] = original_data["Adj Close"].ewm(halflife=short_window).mean()
    df_ema['slow_close'] = original_data["Adj Close"].ewm(halflife=long_window).mean()
    # Construct a crossover trading signal
    df_ema['crossover_long'] = np.where(df_ema['fast_close'] > df_ema['slow_close'], 1.0, 0.0)
    df_ema['crossover_short'] = np.where(df_ema['fast_close'] < df_ema['slow_close'], -1.0, 0.0)
    df_ema['crossover_signal'] = df_ema['crossover_long'] + df_ema['crossover_short']
    
    return df_ema

In [8]:
ema().head()

,fast_close,slow_close,crossover_long,crossover_short,crossover_signal
Date,,,,,
2001-01-02,0.228800,0.228800,0.0,0.0,0.0
2001-01-03,0.240669,0.240490,1.0,0.0,1.0
2001-01-04,0.248351,0.248005,1.0,0.0,1.0
2001-01-05,0.249309,0.249011,1.0,0.0,1.0
2001-01-08,0.250528,0.250222,1.0,0.0,1.0

#### 2. EMA of Daily Return Volatility
The upper band shows a level that is statistically high or expensive
<br>The lower band shows a level that is statistically low or cheap
<br>The Bollinger band width correlates to the volatility of the market

Therefore:
<br>In a more volatile market, Bollinger bands widen
<br>In a less volatile market, the bands narrow

When a short-window (fast) EMA of daily return volatility is greater than a long-window (slow) EMA of daily return volatility, <br> the crossover suggests that a short
opportunity exists where daily return volatility is expected to rise.<br>
This is because during times of rising price volatility, <br> there often exists a negative price bias (selling), and vice versa for when daily return volatility is expected to fall (buying).

As suggusted, 20-day Bollinger band calculation period is a good starting point
<br>https://admiralmarkets.com/education/articles/forex-strategy/three-bollinger-bands-strategies-that-you-need-to-know

In [9]:
def volatility(short_window=12, long_window=26):
    df_vol = pd.DataFrame()
    # Construct a `Fast` and `Slow` Exponential Moving Average from short and long windows, respectively
    df_vol['fast_vol'] = original_data["Adj Close"].ewm(halflife=short_window).std()
    df_vol['slow_vol'] = original_data["Adj Close"].ewm(halflife=long_window).std()
    # Construct a crossover trading signal (the bigger the spike, more likely is selling)
    df_vol['vol_trend_long'] = np.where(df_vol['fast_vol'] < df_vol['slow_vol'], 1.0, 0.0)
    df_vol['vol_trend_short'] = np.where(df_vol['fast_vol'] > df_vol['slow_vol'], -1.0, 0.0) 
    df_vol['vol_trend_signal'] = df_vol['vol_trend_long'] + df_vol['vol_trend_short']
    return df_vol

In [10]:
volatility().head()

,fast_vol,slow_vol,vol_trend_long,vol_trend_short,vol_trend_signal
Date,,,,,
2001-01-02,NaN,NaN,0.0,0.0,0.0
2001-01-03,0.016315,0.016315,0.0,0.0,0.0
2001-01-04,0.017084,0.017151,1.0,0.0,1.0
2001-01-05,0.013863,0.014047,1.0,0.0,1.0
2001-01-08,0.012097,0.012364,1.0,0.0,1.0

#### 3. Bollinger Bands
When the asset closing price is less than the lower band, is a long opportunity.
<br>When the asset closing price is higher than the upper band, is a short opportunity.
<br>As the signal suggests that the price action will tend to move towards to the mean.

In [11]:
def bb(bollinger_window = 20):
    df_bb = pd.DataFrame()
    # Calculate rolling mean and standard deviation
    df_bb['bollinger_mid_band'] = original_data["Adj Close"].ewm(halflife= bollinger_window).mean()
    df_bb['bollinger_std'] = original_data["Adj Close"].ewm(halflife= bollinger_window).std()

    # Calculate upper and lowers bands of bollinger band (Two Standard Deviations)
    df_bb['bollinger_upper_band']  = df_bb['bollinger_mid_band'] + (df_bb['bollinger_std'] * 2)
    df_bb['bollinger_lower_band']  = df_bb['bollinger_mid_band'] - (df_bb['bollinger_std'] * 2)

    # Calculate bollinger band trading signal
    df_bb['bollinger_long'] = np.where(original_data["Adj Close"] < df_bb['bollinger_lower_band'], 1.0, 0.0)
    df_bb['bollinger_short'] = np.where(original_data["Adj Close"] > df_bb['bollinger_upper_band'], -1.0, 0.0)
    df_bb['bollinger_signal'] = df_bb['bollinger_long'] + df_bb['bollinger_short'] 
    return df_bb

In [12]:
bb().head()

,bollinger_mid_band,bollinger_std,bollinger_upper_band,bollinger_lower_band,bollinger_long,bollinger_short,bollinger_signal
Date,,,,,,,
2001-01-02,0.228800,NaN,NaN,NaN,0.0,0.0,0.0
2001-01-03,0.240536,0.016315,0.273165,0.207906,0.0,0.0,0.0
2001-01-04,0.248094,0.017134,0.282362,0.213826,0.0,0.0,0.0
2001-01-05,0.249088,0.014000,0.277088,0.221089,0.0,0.0,0.0
2001-01-08,0.250302,0.012296,0.274893,0.225710,0.0,0.0,0.0

#### 4. On Balance Volume
On Balance Volume (OBV) measures buying and selling pressure as a cumulative indicator, adding volume on up days and subtracting it on down days.
<br>The idea behind the indicator is that price follows volume, a widely held belief among many technical analysts.
<br>OBV Indicator is a momentum based indicator which measures volume flow to gauge the direction of the trend. 
<br>OBV is used as a confirmation tool with regards to price trends. If the OBV increases with respect to the increasing price trend, it can be inferred that the price trend is sustainable. If, however, the OBV shows a decline with respect to the increasing price trend, then it could signal a price trend reversal.

https://school.stockcharts.com/doku.php?id=technical_indicators:on_balance_volume_obv
<br>https://blog.quantinsti.com/indicators-build-trend-following-strategy/
<br>https://www.daytrading.com/obv

In [ ]:
def obv(OBV_ewm_window=20):
    OBV = [0] # initialization with starting OBV = 0
    df_ob = original_data.copy()
    
    # Part I: Calculating OBV:
    # Loop through the data set (close price) from the second row to the end of the data set
    for i in range(1, len(original_data["Adj Close"])):
        if original_data["Adj Close"][i] > original_data["Adj Close"][i-1]:    
            OBV.append(OBV[-1] + original_data["Volume"][i])
        elif original_data["Adj Close"][i] < original_data["Adj Close"][i-1]:
            OBV.append(OBV[-1] - original_data["Volume"][i])
        else:    
            OBV.append(OBV[-1])
    
    # Part II: Store the OBA  and OBV EMA into new columns:
    df_ob['OBV'] = OBV
    df_ob['OBV_EMA'] = df_ob['OBV'].ewm(halflife=OBV_ewm_window).mean()
    
    # Part III: Creating Trading Singnals:

In [14]:
def buy_sell(df, col1, col2):
    sigPriceBuy = []
    sigPriceSell = []
    flag = -1 # for upward or downward trend
    # Loop Through the length of the data set
    for i in range(0, len(df)):
        # if OBV > OBV_EMA then Buy, col1 is the OBV and col2 is the OBV_EMA
        if df[col1][i] > df[col2][i] and flag != 1:
            sigPriceBuy.append(df['Close'][i])
            sigPriceSell.append(np.nan)
            flag = 1
        # if OBV < OBV_EMA then Sell
        elif df[col1][i] < df[col2][i] and flag != 0:
            sigPriceSell.append(df['Close'][i])
            sigPriceBuy.append(np.nan)
            flag = 0
        else:
            sigPriceSell.append(np.nan)
            sigPriceBuy.append(np.nan)
        
    return [sigPriceSell, sigPriceBuy]

In [15]:
# Create buy and sell columns:
x = buy_sell(df_ob,'OBV','OBV_EMA')
df_ob['Buy_Signal_Price'] = x[0]
df_ob["Sell_Signal_Price"] = x[1]
df_ob.head()

,Open,High,Low,Close,Adj Close,Volume,OBV,OBV_EMA,Buy_Signal_Price,Sell_Signal_Price
Date,,,,,,,,,,
2001-01-02,0.265625,0.272321,0.260045,0.265625,0.228800,452312000,0,0.000000e+00,NaN,NaN
2001-01-03,0.258929,0.297991,0.257813,0.292411,0.251872,817073600,817073600,4.156155e+08,NaN,0.292411
2001-01-04,0.323940,0.330357,0.300223,0.304688,0.262447,739396000,1556469600,8.091533e+08,NaN,NaN
2001-01-05,0.302455,0.310268,0.286830,0.292411,0.251872,412356000,1144113600,8.972957e+08,NaN,NaN
2001-01-08,0.302455,0.303292,0.284598,0.295759,0.254756,373699200,1517812800,1.030147e+09,NaN,NaN

In [16]:
# # The pupose of this trading method is to generate a trading signal when an insider buys or sells a stock in their own company. 

# # Initialise API
# info = requests.get(f'https://financialmodelingprep.com/api/v4/insider-trading?symbol={ticker}&limit=10000&apikey=e8ac3c3d2405f465935cd797c342b129')
# info=info.json()
# df = pd.DataFrame(info)
# df