# **Trading Strategies and Signals**

### Initial Imports:

In [1]:
import numpy as np
import pandas as pd


from pathlib import Path
import requests



import warnings
warnings.filterwarnings('ignore')

In [2]:
# !pip install yfinance
import yfinance as yf

### Initialization:

In [3]:
# User Inputs for Stock Ticker and Timeframe:
ticker = "AAPL"
start="2011-01-01"
end="2021-1-1"

In [4]:
# EMA & EMA of returns volatility:
short_window = 12
long_window = 26

# Bollinger Band:
bollinger_window = 20

# On Balance Volumn:
OBV_ewm_window = 20

### Download Stock Data from Yahoo Finance and Calculate Returns:

In [5]:
def get_stock_returns (ticker, start, end):
    ''' 
    Taking ticker, start data, end data,
    Download stock data from yahoo finance,
    Return a list of two dataframes:
    1. the original dataframe
    2. a modified dataframe which contains Adj Close, Volume, and calculated daily returns.
    '''
    df_yfinance = yf.download(ticker, start, end)
    df_returns = df_yfinance[["Adj Close", "Volume"]]
    # calculate returns according to the ticker name
    df_returns["Returns"] = df_yfinance[["Adj Close"]].pct_change()
    df_returns.dropna(inplace=True)
    # rename columns according to the ticker name
    df_returns.columns = [(f"{ticker}_"+ column) for column in df_returns.columns]
    return [df_yfinance, df_returns]

In [6]:
# Inspection of download stock data
original_data, returns_df = get_stock_returns(ticker, start, end)

display(original_data.head())
print(" ")
display(original_data.tail())
print(" ")
print("***************** Check Data Quality *****************")
print(original_data.info())
print(" ")
print(original_data.index)
print(" ")
print("***************** Check Returns Data *****************")
display(returns_df.head())
print(returns_df.shape)

[*********************100%***********************]  1 of 1 completed

                 Open       High        Low      Close  Adj Close     Volume
Date
2010-12-31  11.533929  11.552857  11.475357  11.520000   9.922909  193508000
2011-01-03  11.630000  11.795000  11.601429  11.770357  10.138556  445138400
2011-01-04  11.872857  11.875000  11.719643  11.831786  10.191467  309080800
2011-01-05  11.769643  11.940714  11.767857  11.928571  10.274836  255519600
2011-01-06  11.954286  11.973214  11.889286  11.918929  10.266529  300428800

,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,
2020-12-23,132.160004,132.429993,130.779999,130.960007,130.764603,88223700
2020-12-24,131.320007,133.460007,131.100006,131.970001,131.773087,54930100
2020-12-28,133.990005,137.339996,133.509995,136.690002,136.486053,124486200
2020-12-29,138.050003,138.789993,134.339996,134.869995,134.668762,121047300
2020-12-30,135.580002,135.990005,133.399994,133.720001,133.520477,96452100

***************** Check Data Quality *****************
<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 2517 entries, 2010-12-31 to 2020-12-30
Data columns (total 6 columns):
Open         2517 non-null float64
High         2517 non-null float64
Low          2517 non-null float64
Close        2517 non-null float64
Adj Close    2517 non-null float64
Volume       2517 non-null int64
dtypes: float64(5), int64(1)
memory usage: 137.6 KB
None

DatetimeIndex(['2010-12-31', '2011-01-03', '2011-01-04', '2011-01-05',
               '2011-01-06', '2011-01-07', '2011-01-10', '2011-01-11',
               '2011-01-12', '2011-01-13',
               ...
               '2020-12-16', '2020-12-17', '2020-12-18', '2020-12-21',
               '2020-12-22', '2020-12-23', '2020-12-24', '2020-12-28',
               '2020-12-29', '2020-12-30'],
              dtype='datetime64[ns]', name='Date', length=2517, freq=None)

***************** Check Returns Data *****************

            AAPL_Adj Close  AAPL_Volume  AAPL_Returns
Date
2011-01-03       10.138556    445138400      0.021732
2011-01-04       10.191467    309080800      0.005219
2011-01-05       10.274836    255519600      0.008180
2011-01-06       10.266529    300428800     -0.000808
2011-01-07       10.340052    311931200      0.007161

(2516, 3)

### **Trading Signals:**

#### 1. Exponential Moving Average (EMA) Crossover Strategy:
When the short period EMA cuts above the longer period EMA, it is a bullish signal.
<br>When the short period EMA cuts below the longer period EMA, it is a bearish signal. 

Commonly used periods are 12 and 26 periods. (*set as default in this notebook*)

Although, it indicates present trend of the stock, there are many limitations such as:
<br>a. It has the lagging indicator as it relies on some past price movements. 
<br>b. It is more vulnerable to false signals and getting whipsawed back and forth

https://www.warriortrading.com/exponential-moving-average/<br>
https://www.perfecttrendsystem.com/blog_mt4/en/ema-12-ema-26-trading-strategy

In [7]:
def ema(short_window=12, long_window=26):
    df_ema = pd.DataFrame()
    # Construct a `Fast` and `Slow` Exponential Moving Average from short and long windows, respectively
    df_ema['fast_close'] = original_data["Adj Close"].ewm(halflife=short_window).mean()
    df_ema['slow_close'] = original_data["Adj Close"].ewm(halflife=long_window).mean()
    # Construct a crossover trading signal
    df_ema['crossover_long'] = np.where(df_ema['fast_close'] > df_ema['slow_close'], 1.0, 0.0)
    df_ema['crossover_short'] = np.where(df_ema['fast_close'] < df_ema['slow_close'], -1.0, 0.0)
    df_ema['crossover_signal'] = df_ema['crossover_long'] + df_ema['crossover_short']
    
    return df_ema

In [8]:
ema().head()

,fast_close,slow_close,crossover_long,crossover_short,crossover_signal
Date,,,,,
2010-12-31,9.922909,9.922909,0.0,0.0,0.0
2011-01-03,10.033845,10.032169,1.0,0.0,1.0
2011-01-04,10.089448,10.086690,1.0,0.0,1.0
2011-01-05,10.139885,10.135624,1.0,0.0,1.0
2011-01-06,10.168221,10.163219,1.0,0.0,1.0

#### 2. EMA of Daily Return Volatility
The upper band shows a level that is statistically high or expensive
<br>The lower band shows a level that is statistically low or cheap
<br>The Bollinger band width correlates to the volatility of the market

Therefore:
<br>In a more volatile market, Bollinger bands widen
<br>In a less volatile market, the bands narrow

When a short-window (fast) EMA of daily return volatility is greater than a long-window (slow) EMA of daily return volatility, <br> the crossover suggests that a short
opportunity exists where daily return volatility is expected to rise.<br>
This is because during times of rising price volatility, <br> there often exists a negative price bias (selling), and vice versa for when daily return volatility is expected to fall (buying).

As suggusted, 20-day Bollinger band calculation period is a good starting point
<br>https://admiralmarkets.com/education/articles/forex-strategy/three-bollinger-bands-strategies-that-you-need-to-know

In [9]:
def volatility(short_window=12, long_window=26):
    df_vol = pd.DataFrame()
    # Construct a `Fast` and `Slow` Exponential Moving Average from short and long windows, respectively
    df_vol['fast_vol'] = original_data["Adj Close"].ewm(halflife=short_window).std()
    df_vol['slow_vol'] = original_data["Adj Close"].ewm(halflife=long_window).std()
    # Construct a crossover trading signal (the bigger the spike, more likely is selling)
    df_vol['vol_trend_long'] = np.where(df_vol['fast_vol'] < df_vol['slow_vol'], 1.0, 0.0)
    df_vol['vol_trend_short'] = np.where(df_vol['fast_vol'] > df_vol['slow_vol'], -1.0, 0.0) 
    df_vol['vol_trend_signal'] = df_vol['vol_trend_long'] + df_vol['vol_trend_short']
    return df_vol

In [10]:
volatility().head()

,fast_vol,slow_vol,vol_trend_long,vol_trend_short,vol_trend_signal
Date,,,,,
2010-12-31,NaN,NaN,0.0,0.0,0.0
2011-01-03,0.152485,0.152485,0.0,0.0,0.0
2011-01-04,0.140743,0.141569,1.0,0.0,1.0
2011-01-05,0.148016,0.149224,1.0,0.0,1.0
2011-01-06,0.139413,0.141567,1.0,0.0,1.0

#### 3. Bollinger Bands
When the asset closing price is less than the lower band, is a long opportunity.
<br>When the asset closing price is higher than the upper band, is a short opportunity.
<br>As the signal suggests that the price action will tend to move towards to the mean.

In [11]:
def bb(bollinger_window = 20):
    df_bb = pd.DataFrame()
    # Calculate rolling mean and standard deviation
    df_bb['bollinger_mid_band'] = original_data["Adj Close"].ewm(halflife= bollinger_window).mean()
    df_bb['bollinger_std'] = original_data["Adj Close"].ewm(halflife= bollinger_window).std()

    # Calculate upper and lowers bands of bollinger band (Two Standard Deviations)
    df_bb['bollinger_upper_band']  = df_bb['bollinger_mid_band'] + (df_bb['bollinger_std'] * 2)
    df_bb['bollinger_lower_band']  = df_bb['bollinger_mid_band'] - (df_bb['bollinger_std'] * 2)

    # Calculate bollinger band trading signal
    df_bb['bollinger_long'] = np.where(original_data["Adj Close"] < df_bb['bollinger_lower_band'], 1.0, 0.0)
    df_bb['bollinger_short'] = np.where(original_data["Adj Close"] > df_bb['bollinger_upper_band'], -1.0, 0.0)
    df_bb['bollinger_signal'] = df_bb['bollinger_long'] + df_bb['bollinger_short'] 
    return df_bb

In [12]:
bb().head()

,bollinger_mid_band,bollinger_std,bollinger_upper_band,bollinger_lower_band,bollinger_long,bollinger_short,bollinger_signal
Date,,,,,,,
2010-12-31,9.922909,NaN,NaN,NaN,0.0,0.0,0.0
2011-01-03,10.032600,0.152485,10.337571,9.727630,0.0,0.0,0.0
2011-01-04,10.087402,0.141359,10.370119,9.804684,0.0,0.0,0.0
2011-01-05,10.136723,0.148918,10.434559,9.838888,0.0,0.0,0.0
2011-01-06,10.164515,0.141021,10.446557,9.882473,0.0,0.0,0.0

#### 4. On Balance Volume
On Balance Volume (OBV) measures buying and selling pressure as a cumulative indicator, adding volume on up days and subtracting it on down days.
<br>The idea behind the indicator is that price follows volume, a widely held belief among many technical analysts.
<br>OBV Indicator is a momentum based indicator which measures volume flow to gauge the direction of the trend. 
<br>OBV is used as a confirmation tool with regards to price trends. If the OBV increases with respect to the increasing price trend, it can be inferred that the price trend is sustainable. If, however, the OBV shows a decline with respect to the increasing price trend, then it could signal a price trend reversal.

https://school.stockcharts.com/doku.php?id=technical_indicators:on_balance_volume_obv
<br>https://blog.quantinsti.com/indicators-build-trend-following-strategy/
<br>https://www.daytrading.com/obv

In [13]:
def obv(OBV_ewm_window=20):
    '''
    Using original_data to:
    Part I: Calculating OBV
    Part II: Store the OBA  and OBV EMA into new columns
    Part III: Creating Trading Singnals
    Return a dataframe including OBV signals
    '''
    OBV = [0] # initialization with starting OBV = 0
    df_ob = original_data.copy()
    
    # Part I: Calculating OBV:
    # Loop through the data set (close price) from the second row to the end of the data set
    for i in range(1, len(original_data["Adj Close"])):
        if original_data["Adj Close"][i] > original_data["Adj Close"][i-1]:    
            OBV.append(OBV[-1] + original_data["Volume"][i])
        elif original_data["Adj Close"][i] < original_data["Adj Close"][i-1]:
            OBV.append(OBV[-1] - original_data["Volume"][i])
        else:    
            OBV.append(OBV[-1])
    
    # Part II: Store the OBA  and OBV EMA into new columns:
    df_ob['OBV'] = OBV
    df_ob['OBV_EMA'] = df_ob['OBV'].ewm(halflife=OBV_ewm_window).mean()
    
    # Part III: Creating Trading Singnals:
    df_ob['crossover_long'] = np.where(df_ob['OBV'] > df_ob['OBV_EMA'], 1.0, 0.0)
    df_ob['crossover_short'] = np.where(df_ob['OBV'] < df_ob['OBV_EMA'], -1.0, 0.0)
    df_ob['crossover_signal'] = df_ob['crossover_long'] + df_ob['crossover_short']
    
    return df_ob

In [14]:
obv().head()

,Open,High,Low,Close,Adj Close,Volume,OBV,OBV_EMA,crossover_long,crossover_short,crossover_signal
Date,,,,,,,,,,,
2010-12-31,11.533929,11.552857,11.475357,11.520000,9.922909,193508000,0,0.000000e+00,0.0,0.0,0.0
2011-01-03,11.630000,11.795000,11.601429,11.770357,10.138556,445138400,445138400,2.264256e+08,1.0,0.0,1.0
2011-01-04,11.872857,11.875000,11.719643,11.831786,10.191467,309080800,754219200,4.084881e+08,1.0,0.0,1.0
2011-01-05,11.769643,11.940714,11.767857,11.928571,10.274836,255519600,1009738800,5.667028e+08,1.0,0.0,1.0
2011-01-06,11.954286,11.973214,11.889286,11.918929,10.266529,300428800,709310000,5.972347e+08,1.0,0.0,1.0

#### 5. Insider Trading Signals
The pupose of this trading method is to generate a trading signal when an insider buys or sells a stock in their own company.

In [15]:
# Initialise API
api_key = 'e8ac3c3d2405f465935cd797c342b129'
# Download Data and Transfer into a Dataframe
info = requests.get(f'https://financialmodelingprep.com/api/v4/insider-trading?symbol=TSLA&limit=20000&apikey={api_key}')
info=info.json()
df_insider = pd.DataFrame(info)
# Convert Date to Datetime Object as the Dataframe Index
df_insider['transactionDate'] = pd.to_datetime(df['transactionDate'])
df_insider.set_index('transactionDate', inplace=True)
df.sort_index(ascending=False, inplace=True)